from _common_data_preprocessing import cmd_line
import pickle
import csv




def format(rFile, wFile, sym, topo):
    '''
    Given the following parameters:
    rFile: the file to read from
    wFile: the file to write to
    sym: the type of symmetries to classify by (f or c or n)
    topo: the type of topology to classify by (f or c)
    '''
    global maxSize
    with open(rFile, 'r', newline='') as file:
        reader = csv.reader(file)
        for row in reader:

            '''
            Each line is a crystal in POSCAR format. Here are the indices and their meanings:
            0:    generated by phonopy
            1:    phonopy version
            2-4:  the three axes of the relative coordinate system with 
                    respect to global Cartesian coordinates. Each element is three
                    doubles separated by four spaces, and units in Angstroms
            5:    a list of chemical symbols separated by spaces, each referring to an
                    atom type present in the crystal. For example, Pb_6 Mo_2 O_10 Cl_4
                    would have "Pb Mo O Cl" here.
            6:    a list of integers separated by spaces, each referring to the number
                    of atoms of the corresponding type in the crystal. For example,
                    Pb_6 Mo_2 O_10 Cl_4 would have "6 2 10 4" here.
            7:    "Cartesian" or "Direct", referring to the coordinate system used.
                  Always Direct in this dataset
            8+:   each element is the coordinates of each atom in the crystal, in the 
                    local coordinate system. Each element is three doubles separated 
                    by two spaces, and units are arbitrary (but consistent with the axes).

                    For example (in the case of Pb_6 Mo_2 O_10 Cl_4): the first six elements
                    would be the coordinates of the six Pb atoms, the next two would be the
                    coordinates of the two Mo atoms, the next ten would be the coordinates of
                    the ten O atoms, and the last four would be the coordinates of the four Cl
                    atoms.
            
            
            '''

            

            poscar = list(map(lambda a: a.strip(), row[0].split("\\n")))

            print(poscar)
            exit()

            # outPutls.append(arr)
        
        with open(wFile, 'wb') as wFile:
            pass
            # pickle.dump(outPutls, wFile)


cmd_line(format, "ccnn2")